language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t tbijesse/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tbijesse/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react2"
  env: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-us-west-2-774376362225"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
